=== elpolitecnico-jic/ces3-hechoshistoricos/hHistorico.dtd
<!ELEMENT hechosHistoricos (hechoHistorico)>
<!ATTLIST hechoHistorico descripcion CDATA #REQUIRED>
<!ELEMENT hechoHistorico (fecha, epoca, personajeDestacado)>
<!ELEMENT epoca EMPTY>
<!ELEMENT personajeDestacado ANY>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaDeNacimiento (#PCDATA)>
<!ELEMENT fecha (dia, mes, year)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== elpolitecnico-jic/ces3-hechoshistoricos/hHistorico.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hechosHistoricos SYSTEM "hHistorico.dtd">
<hechosHistoricos>
    <hechoHistorico descripcion="Hola">
        <fecha>
            <formatoFecha>
                <dia>01</dia>
                <mes>01</mes>
                <year>2022</year>
            </formatoFecha>
        </fecha>
        <epoca/>
        <personajeDestacado>
            Test persona <nombre></nombre> y fecha de nacimiento: <fechaDeNacimiento></fechaDeNacimiento>
        </personajeDestacado>
    </hechoHistorico>
    <hechoHistorico descripcion="Hola">
        <fecha>
            2022-10-09
        </fecha>
        <epoca/>
        <personajeDestacado></personajeDestacado>
        <personajeDestacado></personajeDestacado>
    </hechoHistorico>
</hechosHistoricos>
